self.bowl_radius_inner was accessed before it was assigned, and somehow that caused an infinite recursion.  Probably because of __getattr__ overloading in Wrapper.  Not sure how to diagnose.  For now, fixing by not accessing before assigning.
FreeCAD death with it gracefully by setting a max recursion depth.  Rhino just crashed.

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/jjpr/Development/workspace-pycharm-community-3.4.1/barleycorn/barleycorn/examples/scratch_freecad.py", line 29, in expt
    stuff = func(_tk)
  File "/Users/jjpr/Development/workspace-pycharm-community-3.4.1/barleycorn/barleycorn/examples/scratch.py", line 7, in xRS01
    stand = designs.RockerStand01()
  File "/Users/jjpr/Development/workspace-pycharm-community-3.4.1/barleycorn/barleycorn/examples/designs.py", line 11, in __init__
    barleycorn.Wrapper.__init__(self, self.makeMe(), **kwargs)
  File "/Users/jjpr/Development/workspace-pycharm-community-3.4.1/barleycorn/barleycorn/examples/designs.py", line 19, in makeMe
    rim_radius_major = (self.bowl_radius_outer + self.bowl_radius_inner) / 2.0
  File "/Users/jjpr/Development/workspace-pycharm-community-3.4.1/barleycorn/barleycorn/__init__.py", line 101, in __getattr__
    return getattr(self.component, attrname)
... (lots and lots of this)
  File "/Users/jjpr/Development/workspace-pycharm-community-3.4.1/barleycorn/barleycorn/__init__.py", line 101, in __getattr__
    return getattr(self.component, attrname)
RuntimeError: maximum recursion depth exceeded